# -*- coding: utf-8 -*-
"""big.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VTLGjc_5-FpYNE5sv3ay41Jo4JtWA8Gj

# 세팅
"""

# 나눔글꼴 setup
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

# 라이브러리 import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm
import os

from google.colab import drive
drive.mount('/gdrive', force_remount=True)
os.chdir('/gdrive/My Drive/bigdata')
# 구글 드라이브 연결

jan = pd.read_csv("2023_01.csv", encoding='cp949')
feb = pd.read_csv("2023_02.csv", encoding='cp949')

jan.info()

feb.info()

"""# 일최저기온(°C) 상위 10개 (1월, 2월)"""

# 일최저기온(°C) 상위 10개

jan_sorted = jan.sort_values(by='일최저기온(°C)')

top_15_jan = jan_sorted.head(15)

top_15_jan

feb_sorted = feb.sort_values(by='일최저기온(°C)')
top_15_feb = feb_sorted.head(15)
top_15_feb

"""## 1월 그래프"""

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm

# 나눔글꼴 경로 설정 (본인의 환경에 맞게 설정해야 함)
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'

# 나눔글꼴 설정
fontprop = fm.FontProperties(fname=font_path, size=14)

# '일최저기온(°C)' 열을 기준으로 오름차순 정렬하고 상위 10개 행 선택
top_10_lowest_temp = jan.sort_values(by='일최저기온(°C)').head(10)

# 그래프 생성 (꺾은선 그래프)
plt.figure(figsize=(12, 8))
sns.lineplot(x='지점', y='일최저기온(°C)', data=top_10_lowest_temp, marker='o', palette='viridis')

# 그래프 제목 및 축 레이블 설정 (나눔글꼴 적용)
plt.title('1월 상위 10개 지역별 일최저기온(°C)', fontproperties=fontprop)
plt.xlabel('지점', fontproperties=fontprop)
plt.ylabel('일최저기온(°C)', fontproperties=fontprop)

# 마이너스 기호 표시 수정
plt.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 깨짐 방지

# 그래프 표시
plt.show()

"""## 2월 그래프"""

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm

# 나눔글꼴 경로 설정 (본인의 환경에 맞게 설정해야 함)
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'

# 나눔글꼴 설정
fontprop = fm.FontProperties(fname=font_path, size=14)

# '일최저기온(°C)' 열을 기준으로 오름차순 정렬하고 상위 10개 행 선택
top_10_lowest_temp_1 = feb.sort_values(by='일최저기온(°C)').head(14) # 중복잘리는거 제외하고 10개 출력하게 14로 변경

# 그래프 생성 (꺾은선 그래프)
plt.figure(figsize=(12, 8))
sns.lineplot(x='지점', y='일최저기온(°C)', data=top_10_lowest_temp_1, marker='o', palette='viridis')

# 그래프 제목 및 축 레이블 설정 (나눔글꼴 적용)
plt.title('2월 상위 10개 지역별 일최저기온(°C)', fontproperties=fontprop)
plt.xlabel('지점', fontproperties=fontprop)
plt.ylabel('일최저기온(°C)', fontproperties=fontprop)

# 마이너스 기호 표시 수정
plt.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 깨짐 방지

# 그래프 표시
plt.show()

"""# 일최저체감온도(°C)"""

# 일최저체감온도(°C) 상위 10개

jan_sorted_pe = jan.sort_values(by='일최저체감온도(°C)')

top_15_jan_pe = jan_sorted.head(15)

top_15_jan_pe

# 일최저체감온도(°C) 상위 10개

feb_sorted_pe = feb.sort_values(by='일최저체감온도(°C)')

top_15_feb_pe = feb_sorted.head(15)

top_15_feb_pe

"""## 1월 그래프"""

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm

# 나눔글꼴 경로 설정 (본인의 환경에 맞게 설정해야 함)
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'

# 나눔글꼴 설정
fontprop = fm.FontProperties(fname=font_path, size=14)

# '일최저기온(°C)' 열을 기준으로 오름차순 정렬하고 상위 5개 행 선택
top_5_lowest_temp = jan.sort_values(by='일최저기온(°C)').head(10)

# 그래프 생성 (꺾은선 그래프)
plt.figure(figsize=(12, 8))
sns.lineplot(x='지점', y='일최저기온(°C)', data=top_5_lowest_temp, marker='o', palette='viridis')

# 그래프 제목 및 축 레이블 설정 (나눔글꼴 적용)
plt.title('1월 상위 10개 일최저체감온도(°C)', fontproperties=fontprop)
plt.xlabel('지점', fontproperties=fontprop)
plt.ylabel('일최저체감온도(°C)', fontproperties=fontprop)

# 마이너스 기호 표시 수정
plt.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 깨짐 방지

# 그래프 표시
plt.show()

"""## 2월 그래프"""

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm

# 나눔글꼴 경로 설정 (본인의 환경에 맞게 설정해야 함)
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'

# 나눔글꼴 설정
fontprop = fm.FontProperties(fname=font_path, size=14)

# '일최저기온(°C)' 열을 기준으로 오름차순 정렬하고 상위 5개 행 선택
top_5_lowest_temp_1 = feb.sort_values(by='일최저기온(°C)').head(14)

# 그래프 생성 (꺾은선 그래프)
plt.figure(figsize=(12, 8))
sns.lineplot(x='지점', y='일최저기온(°C)', data=top_5_lowest_temp_1, marker='o', palette='viridis')

# 그래프 제목 및 축 레이블 설정 (나눔글꼴 적용)
plt.title('2월 상위 10개 일최저체감온도(°C)', fontproperties=fontprop)
plt.xlabel('지점', fontproperties=fontprop)
plt.ylabel('일최저체감온도(°C)', fontproperties=fontprop)

# 마이너스 기호 표시 수정
plt.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 깨짐 방지

# 그래프 표시
plt.show()

"""## 살기 힘든 지역(1월 기준)"""

# '일최저기온(°C)'와 '일최저체감온도(°C)' 열을 기준으로 오름차순 정렬
coldest_areas = jan.sort_values(by=['일최저기온(°C)', '일최저체감온도(°C)']).head(3)

# 결과 출력
coldest_areas[['지점', '일최저기온(°C)', '일최저체감온도(°C)']]

# 나눔고딕 경로 설정 (본인의 환경에 맞게 설정해야 함)
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'

# 나눔고딕 폰트 설정
fontprop = fm.FontProperties(fname=font_path, size=12)

# '일최저기온(°C)'와 '일최저체감온도(°C)' 열을 기준으로 오름차순 정렬
coldest_areas = jan.sort_values(by=['일최저기온(°C)', '일최저체감온도(°C)']).head(3)

# 꺾은선 그래프 그리기
plt.figure(figsize=(10, 6))
sns.lineplot(data=coldest_areas, x='지점', y='일최저기온(°C)', marker='o', label='일최저기온(°C)')
sns.lineplot(data=coldest_areas, x='지점', y='일최저체감온도(°C)', marker='o', label='일최저체감온도(°C)')

# 그래프 제목 및 축 레이블 설정
plt.title('가장 추운 지역 3곳의 일최저기온과 일최저체감온도', fontproperties=fontprop, fontsize=16)
plt.xlabel('지점', fontproperties=fontprop, fontsize=14)
plt.ylabel('온도 (°C)', fontproperties=fontprop, fontsize=14)

# 범례 추가
plt.legend()

# 나눔고딕 폰트 적용
plt.rcParams['font.family'] = 'NanumGothic'

# 그래프 표시
plt.show()

"""## 살기 힘든 지역(2월 기준)"""

# '일최저기온(°C)'와 '일최저체감온도(°C)' 열을 기준으로 오름차순 정렬
coldest_areas_1 = feb.sort_values(by=['일최저기온(°C)', '일최저체감온도(°C)']).head(5)

# 결과 출력
coldest_areas_1[['지점', '일최저기온(°C)', '일최저체감온도(°C)']]

# 나눔고딕 경로 설정 (본인의 환경에 맞게 설정해야 함)
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'

# 나눔고딕 폰트 설정
fontprop = fm.FontProperties(fname=font_path, size=12)

# '일최저기온(°C)'와 '일최저체감온도(°C)' 열을 기준으로 오름차순 정렬
coldest_areas_1 = feb.sort_values(by=['일최저기온(°C)', '일최저체감온도(°C)']).head(5)

# 꺾은선 그래프 그리기
plt.figure(figsize=(10, 6))
sns.lineplot(data=coldest_areas_1, x='지점', y='일최저기온(°C)', marker='o', label='일최저기온(°C)')
sns.lineplot(data=coldest_areas_1, x='지점', y='일최저체감온도(°C)', marker='o', label='일최저체감온도(°C)')

# 그래프 제목 및 축 레이블 설정
plt.title('가장 추운 지역 3곳의 일최저기온과 일최저체감온도', fontproperties=fontprop, fontsize=16)
plt.xlabel('지점', fontproperties=fontprop, fontsize=14)
plt.ylabel('온도 (°C)', fontproperties=fontprop, fontsize=14)

# 범례 추가
plt.legend()

# 나눔고딕 폰트 적용
plt.rcParams['font.family'] = 'NanumGothic'

# 그래프 표시
plt.show()

"""## 결론

## 가장 추운 지역 top3

### 1. 양구

### 2. 화천

### 3. 철원

## 번외
"""

# '일최고기온(°C)' 열을 기준으로 내림차순 정렬하여 상위 10개 행 선택
top_10_highest_temp = jan.sort_values(by='일최고기온(°C)', ascending=False).head(10)

# 결과를 표로 출력
top_10_highest_temp[['지점', '일최고기온(°C)']]

# '일최고기온(°C)' 열을 기준으로 내림차순 정렬하여 상위 10개 행 선택
top_10_highest_temp_1 = feb.sort_values(by='일최고기온(°C)', ascending=False).head(10)

# 결과를 표로 출력
top_10_highest_temp_1[['지점', '일최고기온(°C)']]

# '일최고기온(°C)' 열을 기준으로 내림차순 정렬하여 상위 10개 행 선택
top_10_highest_temp = jan.sort_values(by='일최고기온(°C)', ascending=False).head(10)

# 나눔고딕 경로 설정 (본인의 환경에 맞게 설정해야 함)
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'

# 나눔고딕 폰트 설정
fontprop = fm.FontProperties(fname=font_path, size=12)

# 꺾은선 그래프 그리기
plt.figure(figsize=(10, 6))
sns.lineplot(data=top_10_highest_temp, x='지점', y='일최고기온(°C)', marker='o', label='일최고기온(°C)')

# 그래프 제목 및 축 레이블 설정
plt.title('상위 10개 지역의 일최고기온(°C)', fontproperties=fontprop, fontsize=16)
plt.xlabel('지점', fontproperties=fontprop, fontsize=14)
plt.ylabel('일최고기온(°C)', fontproperties=fontprop, fontsize=14)

# 범례 추가
plt.legend()

# 나눔고딕 폰트 적용
plt.rcParams['font.family'] = 'NanumGothic'

# 그래프 표시
plt.show()

# '일최고기온(°C)' 열을 기준으로 내림차순 정렬하여 상위 10개 행 선택 (2월)
top_10_highest_temp_feb = feb.sort_values(by='일최고기온(°C)', ascending=False).head(10)

# 나눔고딕 경로 설정 (본인의 환경에 맞게 설정해야 함)
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'

# 나눔고딕 폰트 설정
fontprop = fm.FontProperties(fname=font_path, size=12)

# 꺾은선 그래프 그리기 (2월)
plt.figure(figsize=(10, 6))
sns.lineplot(data=top_10_highest_temp_feb, x='지점', y='일최고기온(°C)', marker='o', label='2월')

# 그래프 제목 및 축 레이블 설정
plt.title('2월 상위 10개 지역의 일최고기온(°C)', fontproperties=fontprop, fontsize=16)
plt.xlabel('지점', fontproperties=fontprop, fontsize=14)
plt.ylabel('일최고기온(°C)', fontproperties=fontprop, fontsize=14)

# 범례 추가
plt.legend()

# 나눔고딕 폰트 적용
plt.rcParams['font.family'] = 'NanumGothic'

# 그래프 표시
plt.show()

"""## 번외 결론(젤 따뜻한 지역)
### 경주가 1월 2월 둘다 따뜻하게 보낼수있다.
"""